apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bot-client.fullname" . }}
  labels:
    {{- include "bot-client.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bot-client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bot-client.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "bot-client.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: WEBCHAT_SECRET
            value: "{{ .Values.healthBot.webchatSecret }}"
          - name: APP_SECRET
            value: "{{ .Values.healthBot.appSecret }}"
          - name: APP_INSIGHTS_KEY
            value: "{{ .Values.healthBot.instrumentationKey }}"
          - name: DIRECTLINE_ENDPOINT_URI
            value: "{{ .Values.healthBot.directLineApiEndpointUri }}"
          - name: SCENARIO_ID
            value: "{{ .Values.healthBot.scenarioId }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
